name: mhufl_common_example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mhufl_common:
    path: ..
  mhudart_common:
    path: ../../mhudart_common
  protobuf: ^2.1.0
  collection: ^1.17.0
  kt_dart: any

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mhudart_generator:
    path: ../../mhudart_generator
  mhudart_generator_base:
    path: ../../mhudart_generator_base

flutter:
  uses-material-design: true

