name: mhufl_common
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  built_collection: ^5.1.1
  flutter:
    sdk: flutter
  logging: ^1.1.1
  retry: ^3.1.0
  rxdart: ^0.27.7
  mhudart_common:
    path: ../mhudart_common
  shared_preferences: ^2.0.17
  logger: ^1.1.0
  protobuf: ^2.1.0
  kt_dart: ^1.0.0
  path: ^1.8.2
  collection: ^1.17.0
  select_dialog: ^2.0.0
  fast_immutable_collections: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mhudart_generator:
    path: ../mhudart_generator
  mhudart_generator_base:
    path: ../mhudart_generator_base


flutter:
